# Site settings
title: Evenly
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Contact details
company_name: Evenly GmbH
address: Oranienstra√üe 6
zip: 10997
city: Berlin
phone: +49 30 60984272
email: hello@evenly.io


# Build settings
markdown: kramdown

collections:
  jobs:
    permalink: /jobs/:path/
    output: true
  projects:
    permalink: /projects/:path/
    output: true
